### ISSUE TITLE
A newer version of the extension available in Wikimedia git

### ISSUE THREAD

**Issue by drorsnir** [Orain/MultiBoilerplate#1]
I have published a new version, 2.0:
https://www.mediawiki.org/wiki/Extension:MultiBoilerplate
https://git.wikimedia.org/summary/?r=mediawiki/extensions/MultiBoilerplate.git

I believe your version is no longer needed.

Regards,
Dror.

**Comment by Arcane21** [comment]
Thanks for the information. Our version was back when it was located on Subversion, good to know we can import an improved git hosted version. :)
